# **Interpolate in Pandas**

In [13]:
import pandas as pd
import numpy as np

In [16]:
# Date format in pandas - YYYY-MM-DD
# Time Format in pandas - HH:MM:SS
# Date-Time format in padnas - YYYY-MM-DD HH:MM:SS

dataset = {
    "timestamp": pd.date_range("2026-04-21 07:00", periods=5, freq="min"),
    "tempreature": [23.65, np.nan, 27.21, None, 30.98]
}

iotDf = pd.DataFrame(dataset)
iotDf

            timestamp  tempreature
0 2026-04-21 07:00:00        23.65
1 2026-04-21 07:01:00          NaN
2 2026-04-21 07:02:00        27.21
3 2026-04-21 07:03:00          NaN
4 2026-04-21 07:04:00        30.98

In [18]:
# here, there are 2 missing values and these values can't be filled by the use of fillna method. why?
# ---> because if we are going to fill a deafult value it may cause some analysis lack through which the insights may vary.

# to agar ye nahi kar sakte to kya kare fir?
# here, in the situation of no-default values where we can't use any default value we'll use interpolation through which the nan or none
# or missing values will be filled through the mean value of the previous and the next value

# to perform interpolation in pandas we are using interpolate method -

iotDf["tempreature"].interpolate()

0    23.650
1    25.430
2    27.210
3    29.095
4    30.980
Name: tempreature, dtype: float64

# **Grouping In Pandas**

- suppose we're having an e-comm dataset in which we've to perform some operations on certain groups. In this scenarios we need to know that how Grouping and Group works in Pandas

In [19]:
dataset = {
    "prodName": [
        "Wireless Headphones", "Bluetooth Speaker", "Smart Watch", "Power Bank", "USB-C Hub", "Gaming Mouse",
        "Water Bottle", "Ceramic Mug Set", "Glass Tumblers", "Dinner Plate Set", "Porcelain Bowl", "Tea Infuser",
        "Denim Mens Jeans", "Cotton T-Shirt", "Hooded Sweatshirt", "Cargo Pants", "Formal Shirt", "Chino Shorts",
        "To-Do Diary", "Gel Pen Set", "Spiral Notebook", "Desk Organizer", "Mechanical Pencil", "Sticky Notes",
        "Women Watch", "Women Perfume", "Leather Belt", "Crossbody Bag", "Sunglasses", "Silk Scarf", "Gold Plated Earrings",
        "kids Sling", "Building Blocks", "Plush Teddy Bear", "Coloring Book Set", "Remote Control Car", "Educational Tablet", "Baby Romper"
    ],
    "prodPrice": [
        1999, 2499, 3499, 899, 1299, 1599,
        59, 450, 299, 1200, 180, 250,
        1199, 499, 1499, 1299, 899, 750,
        259, 150, 120, 550, 89, 45,
        1799, 499, 699, 2100, 1250, 850, 1100,
        149, 899, 599, 299, 1899, 2500, 450
    ],
    "prodCategory": [
        "Electronics", "Electronics", "Electronics", "Electronics", "Electronics", "Electronics",
        "Crockery", "Crockery", "Crockery", "Crockery", "Crockery", "Crockery",
        "Clothing", "Clothing", "Clothing", "Clothing", "Clothing", "Clothing",
        "Stationary", "Stationary", "Stationary", "Stationary", "Stationary", "Stationary",
        "Fashion", "Fashion", "Fashion", "Fashion", "Fashion", "Fashion", "Fashion",
        "Kids", "Kids", "Kids", "Kids", "Kids", "Kids", "Kids"
    ]
}

ecommDf = pd.DataFrame(dataset)

ecommDf

                prodName  prodPrice prodCategory
0    Wireless Headphones       1999  Electronics
1      Bluetooth Speaker       2499  Electronics
2            Smart Watch       3499  Electronics
3             Power Bank        899  Electronics
4              USB-C Hub       1299  Electronics
5           Gaming Mouse       1599  Electronics
6           Water Bottle         59     Crockery
7        Ceramic Mug Set        450     Crockery
8         Glass Tumblers        299     Crockery
9       Dinner Plate Set       1200     Crockery
10        Porcelain Bowl        180     Crockery
11           Tea Infuser        250     Crockery
12      Denim Mens Jeans       1199     Clothing
13        Cotton T-Shirt        499     Clothing
14     Hooded Sweatshirt       1499     Clothing
15           Cargo Pants       1299     Clothing
16          Formal Shirt        899     Clothing
17          Chino Shorts        750     Clothing
18           To-Do Diary        259   Stationary
19           Gel Pen Set        150   Stationary
20       Spiral Notebook        120   Stationary
21        Desk Organizer        550   Stationary
22     Mechanical Pencil         89   Stationary
23          Sticky Notes         45   Stationary
24           Women Watch       1799      Fashion
25         Women Perfume        499      Fashion
26          Leather Belt        699      Fashion
27         Crossbody Bag       2100      Fashion
28            Sunglasses       1250      Fashion
29            Silk Scarf        850      Fashion
30  Gold Plated Earrings       1100      Fashion
31            kids Sling        149         Kids
32       Building Blocks        899         Kids
33      Plush Teddy Bear        599         Kids
34     Coloring Book Set        299         Kids
35    Remote Control Car       1899         Kids
36    Educational Tablet       2500         Kids
37           Baby Romper        450         Kids

In [25]:
catProductGrouping = ecommDf.groupby("prodCategory")['prodName'].count()

catProductGrouping

prodCategory
Clothing       6
Crockery       6
Electronics    6
Fashion        7
Kids           7
Stationary     6
Name: prodName, dtype: int64

In [34]:
priceByCategory = ecommDf.groupby("prodCategory")['prodPrice'].sum()

priceByCategory

prodCategory
Clothing        6145
Crockery        2438
Electronics    11794
Fashion         8297
Kids            6795
Stationary      1213
Name: prodPrice, dtype: int64